apps/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart, name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('checkout/',views.checkout,name="checkout"),
]

musicpro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


# admin.site.enable_nav_sidebar = False
from . import views

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('tienda/',include('apps.tienda.urls')),
    path('cart/',include('apps.carts.urls')),
    path('accounts/',include('apps.accounts.urls')),
    path('pedidos/',include('apps.orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Administración MusicPro"
admin.site.site_title = "MusicPro" 
admin.autodiscover()

apps/carts/models.py
from apps.tienda.models import Variation,Product
from django.db import models
from apps.accounts.models import Account
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank = True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    class Meta:
        verbose_name = 'Carrito'
        verbose_name_plural = 'Carritos'

    
class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE,null=True,verbose_name="usuario")
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name="producto")
    variations = models.ManyToManyField(Variation,blank=True,verbose_name="Variaciones")
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,null=True,verbose_name="carrito")
    quantity = models.IntegerField("Cantidad")
    is_active = models.BooleanField(default=True,verbose_name="¿Está activo?")

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product
    class Meta:
        verbose_name = 'ItemCarrito'
        verbose_name_plural = 'ItemCarritos'
    

apps/tienda/models.py
from typing import DefaultDict
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    category_name = models.CharField("Nombre categoria",max_length=50,unique=True)
    slug = models.SlugField(max_length=100,unique=True)
    description = models.TextField("Descripcion",max_length=255,blank=True)
    cat_image = models.ImageField("Imagen categoria",upload_to='photos/categories', blank=True)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def get_url(self):
        return reverse('products_by_category',args=[self.slug])

    def __str__(self):
        return self.category_name

class Marca(models.Model):
    marca_name = models.CharField("nombre marca",max_length=200,unique=True)
    description = models.TextField("descripcion",max_length=500,blank=True)
    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __str__(self):
        return self.marca_name

class Product(models.Model):
    product_name = models.CharField("nombre producto",max_length=200,unique=True)
    slug = models.SlugField(max_length=200,unique=True)
    description = models.TextField("descripcion",max_length=500,blank=True)
    price = models.IntegerField("precio")
    images = models.ImageField("imagenes",upload_to='photos/products',null=True)
    stock = models.IntegerField()
    is_available = models.BooleanField("disponible",default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name = 'Categoria')
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT,null=True,verbose_name = 'Marca')
    
    # Agregar serial.
    created_date = models.DateField("Fecha creación",auto_now_add=True)
    modified_date = models.DateField("Fecha modificación",auto_now_add=True)

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.product_name


variation_category_choice = (
    ('color','Color'),
    ('size','Tamaño')
)

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)

class Variation(models.Model):
    product = models.ForeignKey(Product,verbose_name="Producto",on_delete=models.CASCADE)
    variation_category = models.CharField("Categoría variación",max_length=100,choices=variation_category_choice)
    variation_value = models.CharField("Valor variación",max_length=100)
    is_active = models.BooleanField("¿Está activa?",default=True)
    created_date = models.DateTimeField("Fecha de creación",auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value
    
    class Meta:
        verbose_name = 'Variación'
        verbose_name_plural = 'Variaciones'

apps/carts/views.py
from django.conf import settings
from django.contrib.auth import login
from django.shortcuts import redirect, render, get_object_or_404
from apps.tienda.models import Product,Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
# Create your views here.

# Constantes

Desc = settings.DESCUENTO


# Funciones

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) #get the product
    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')
    # If the user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing_variations -> database
            # current variation -> product_variation
            # item_id -> database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            print(ex_var_list)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('cart')


def remove_cart(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')



def cart(request, total=0, quantity=0, cart_items=None):
    descuento = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
            
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        if request.user.is_authenticated and (quantity >= 4):
            descuento = int((Desc * total)/100)
        grand_total = total - descuento
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'descuento': descuento,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    descuento = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        if request.user.is_authenticated and (quantity >= 4):
            descuento = int((Desc * total)/100)
        grand_total = total - descuento
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'descuento': descuento,
        'grand_total': grand_total,
    }
    return render(request,'store/checkout.html',context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->

    {% if not cart_items %}
    <h2 class="text-center">Tu carrito de compras está vacio</h2>
    <br>
    <div class="text-center">
      <a href="{% url 'store' %}" class="btn btn-primary">Continuar Comprando</a>
    </div>
    {% else %}


    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Productos</th>
                <th scope="col" width="120">Cantidad</th>
                <th scope="col" width="120">Valor</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>

              {% for cart_item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm">
                    </div>
                    <figcaption class="info">
                      <a href="{{ cart_item.product.get_url}}" class="title text-dark">{{ cart_item.product.product_name }}</a>

                      <p class="text-muted small">
                        Código producto:NA00000155{{cart_item.product.id}}
                        <br>{% if cart_item.variations.all %}
                        {% for item in cart_item.variations.all %}
                        {{ item.get_variation_category_display }} :
                        {{ item.variation_value}}
                        <br>
                        {% endfor %}

                        {% endif %}</p>

                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
                      </div>
                      <input type="text" class="form-control" value="{{ cart_item.quantity }}">
                      <div class="input-group-append">
                        <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                          {% csrf_token %}
                          {% for item in cart_item.variations.all %}
                          <input type="hidden" name="{{item.variation_category | lower }}" value="{{ item.variation_value | capfirst}}">
                          {% endfor %}
                          <button class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i> </button>
                        </form>
                      </div>
                    </div> <!-- input-group.// -->
                  </div> <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">${{ cart_item.sub_total | intcomma}}</var>
                    <small class="text-muted"> ${{ cart_item.product.price | intcomma }} c/u
                    </small>
                  </div> <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('¿Estás seguro que quieres borrar este item?')" class="btn btn-danger">
                    Remover</a>
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      <aside class="col-lg-3">

        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total:</dt>
              <dd class="text-right">${{total | intcomma}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Descuento:</dt>
              <dd class="text-right"> ${{descuento | intcomma}}</dd>
            </dl>
            <dl class="dlist-align">
              <dt>Total a pagar:</dt>
              <dd class="text-right text-dark b"><strong>${{grand_total | intcomma}}</strong></dd>
            </dl>
            <hr>
            <p class="text-center mb-3">
              {% comment %} <img src="{% static 'images/misc/webpay.png' %}" height="90"> {% endcomment %}
            </p>
            <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Confirmar </a>
            <a href="{% url 'store' %}" class="btn btn-light btn-block">Continuar Comprando</a>
          </div> <!-- card-body.// -->
        </div> <!-- card.// -->

      </aside> <!-- col.// -->

    </div> <!-- row.// -->

    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->

  </div> <!-- container .//  -->
</section>


{% endblock content %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load humanize %}
<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->

    <div class="row">
      <aside class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h4 clas="card-title mb-4"> Dirección de Envio </h4>
            <form action="{% url 'place_order' %}" method="POST" id="form-direccion">
              {% csrf_token %}
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Nombre</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="col form-grup">
                  <label for="">Apellido</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Región</label>
                  <input type="text" name="region" class="form-control" required>
                </div>
                <div class="col form-grup">
                  <label for="">Comuna</label>
                  <input type="text" name="comuna" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Calle</label>
                  <input type="text" name="calle" class="form-control" required>
                </div>
                <div class="col form-grup">
                  <label for="">Num. Calle</label>
                  <input type="text" name="num_calle" class="form-control" required>
                </div>
              </div>
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Block</label>
                  <input type="text" name="block" class="form-control">
                </div>
                <div class="col form-grup">
                  <label for="">Núm. Dpto</label>
                  <input type="text" name="num_dpto" class="form-control">
                </div>
              </div>
              <div class="form-row">
                <div class="col form-grup">
                  <label for="">Comentarios adicionales</label>
                  <textarea type="text" name="comentarios" class="form-control"></textarea>
                </div>
              </div>
            </form>
          </div>
        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      <aside class="col-lg-6">

        <div class="card">
          <div class="card-body">
            <table class="table table-borderless table-shopping-cart">
              <thead class="text-muted">
                <tr class="small text-uppercase">
                  <th scope="col">Productos</th>
                  <th scope="col" width="120">Cantidad</th>
                  <th scope="col" width="120">Valor</th>
                  <th scope="col" class="text-right" width="200"> </th>
                </tr>
              </thead>
              <tbody>

                {% for cart_item in cart_items %}
                <tr>
                  <td>
                    <figure class="itemside align-items-center">
                      <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm">
                      </div>
                      <figcaption class="info">
                        <a href="{{ cart_item.product.get_url}}" class="title text-dark">{{ cart_item.product.product_name }}</a>

                        <p class="text-muted small">{% if cart_item.variations.all %}
                          {% for item in cart_item.variations.all %}
                          {{ item.get_variation_category_display }} :
                          {{ item.variation_value}}
                          <br>
                          {% endfor %}
                          {% endif %}</p>

                      </figcaption>
                    </figure>
                  </td>
                  <td>
                    <p class="text-center">{{ cart_item.quantity }}</p>
                  </td>
                  <td>
                    <div class="price-wrap">
                      <var class="price">${{ cart_item.sub_total | intcomma}}</var>
                      <small class="text-muted"> ${{ cart_item.product.price | intcomma }} c/u
                      </small>
                    </div> <!-- price-wrap .// -->
                  </td>
                </tr>
                {% endfor %}

              </tbody>
            </table>

            <button type="submit" name="submit" form="form-direccion" class="btn btn-primary btn-block">Realizar pedido</button>
            <a href="{% url 'store' %}" class="btn btn-light btn-block">Continuar Comprando</a>
          </div> <!-- card-body.// -->
        </div> <!-- card.// -->

      </aside> <!-- col.// -->

    </div> <!-- row.// -->

    <!-- ============================ COMPONENT 1 END .// ================================= -->

  </div> <!-- container .//  -->
</section>


{% endblock content %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{ single_product.images.url }}"></a>
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
            <article class="content-body">

              <h2 class="title">{{ single_product.product_name }}</h2>

              <div class="mb-3">
                <var class="price h4">${{ single_product.price | intcomma }}</var><br>
                <var class="stock h5">Stock: {{ single_product.stock | intcomma }}</var>
              </div>

              <p>{{ single_product.description }}</p>
              {% if single_product.variation_set.all %}
              {% if single_product.variation_set.sizes %}
              <div class="row">
                <div class="item-option-select" <h6>Tamaño</h6>
                  <select name="size" id="" class="form-control" required>
                    <option value="" disabled selected>Seleccione Tamaño </option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{ i.variation_value | lower}}">
                      {{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              {% endif %}
              {% if single_product.variation_set.colors %}
              <div class="row">
                <div class="item-option-select">
                  <h6>Color</h6>
                  <select name="color" id="" class="form-control" required>
                    <option value="" disabled selected>Seleccione Color</option>
                    {% for i in single_product.variation_set.colors %}
                    <option value="{{ i.variation_value | lower }}">
                      {{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div> <!-- row.// -->
              {% endif %}
              {% endif %}
              <hr>

              {% if single_product.stock <= 0 %}
              <h5 class="text-danger">Agotado</h5>
              {% else %}
              <button type="submit" class="btn  btn-primary"><span class="text">Añadir al carrito</span>
                <i class="fas fa-shopping-cart"></i> </button>
              {% endif %}
            </article> <!-- product-info-aside .// -->
          </form>
        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">

        <header class="section-heading">
          <h3>Reseñas</h3>

        </header>

        <article class="box mb-3">
          <div class="icontext w-100">
            <img src="{% static 'images/avatars/avatar1.jpg'%}" class="img-xs icon rounded-circle">
            <div class="text">
              <span class="date text-muted float-md-right">24.05.2021 </span>
              <h6 class="mb-1">David Larrondo</h6>

            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <p>
              Etrec diyalanan Mulai bacutumbu Sapuchindendorran Seia bilaun fakiu Papironpo otac
              Shutrapagueloguica Trataoromo bucherre sanpepajasa Mutabukatanaitatutu Sapidapuchi
              Dorronchiapa Derrimana Anakchiapa Maudisaia Coringarrini Anacbansat Barrishguen Mukakaya
              Parrishnia Patum Okalo kaurin Yananguopanuapbur barys barys
            </p>
          </div>
        </article>



      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}